# Configuration for https://probot.github.io/apps/auto-assign

addReviewers: true
addAssignees: false

reviewers:
  - sohkai

skipKeywords:
  - wip
  - draft

# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0
