language: node_js
cache: npm
notifications:
  email: false
node_js:
  - 'lts/*'
before_script:
  - npm prune
install:
  - npm install
script:
  - npm run lint
  - npm run build
  - npm run test
  - npm run size
after_success:
  - ./node_modules/.bin/lcov-result-merger 'packages/*/coverage/lcov.info' | ./node_modules/.bin/coveralls
