export const FORCE_LOCAL_STORAGE = Symbol('FORCE_LOCAL_STORAGE')
export const SUBSCRIPTION_EVENT_DELAY = Symbol('SUBSCRIPTION_EVENT_DELAY')
export const CACHE_TRACKER_PREFIX = "cacheTracker"
export const CACHE_TRACKER_CACHES_KEY = "caches"