name: CI

on: push

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Lint
      run: yarn lint
    - name: test
      run: |
        yarn test
        # Merge coverage into a local coverage file
        npx lcov-result-merger 'packages/*/coverage/lcov.info' './merged-lcov.info'
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: './merged-lcov.info'
    - name: size-limit
      run: |
        yarn build
        yarn size
env:
  CI: true
